### ISSUE TITLE
Invalid CQL when querying with composite keys

### ISSUE THREAD

**Issue by ehartsuyker** [websudos/phantom#165]
I am using Phantom v.1.2.7 with Scala v.2.11.2 and Cassandra v.2.1.

My table looks like this.
```sql
CREATE TABLE LogLooklUpTable (
  type text,
  yearmonth int,
  eventId timeuuid,
  objectId INT,
  PRIMARY KEY ((type, yearmonth), event_id)
);
```
```scala
case class LogKey(eventId: UUID, objectId: Int)
class LogLookUpTable extends CassandraTable[LogLookUpTable, LogKey] with CassandraConnector {

  object typ extends StringColumn(this) with PartitionKey[String]
  object yearmonth extends IntColumn(this) with PartitionKey[Int]
  object eventId extends TimeUUIDColumn(this) with PrimaryKey[UUID]
  object objectId extends IntColumn(this)

  def fromRow(row: Row) = LogKey(eventId(row), objectId(row))

}
```

And my query looks like this.
```scala
select.where(_.typ eqsToken typ)
  .and(_.yearmonth eqsToken yearMonth)
  .consistencyLevel_=(ConsistencyLevel.ALL)
  .fetchEnumerator()
```

Which on execution generates the following CQL:
```sql
SELECT * FROM LogLookUpTable WHERE token(type)=token('<type>') AND token(yearmonth)=token(<yearmonth>)
```

On execution it throws the following exception:
```
com.datastax.driver.core.exceptions.InvalidQueryException: Invalid number of arguments in call to function token: 2 required but 1 provided
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:97)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:110)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:237)
	at com.datastax.driver.core.RequestHandler.onSet(RequestHandler.java:390)
	at com.datastax.driver.core.Connection$Dispatcher.messageReceived(Connection.java:645)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
The valid CQL as determined from cqlsh is either of the following:
```sql
SELECT * FROM LogLookUpTable WHERE token(type, yearmonth)=token('<type>', <yearmonth>)
SELECT * FROM LogLookUpTable WHERE type = '<type>' and yearmonth = <yearmonth>
```

Is there a way to model the above valid CQL statement using the Phantom DSL? I looked at the source code, and so far the only way I have been able to make it work is by using the underlying Java library directly.

**Comment by alexflav23** [comment]
@ehartsuyker Apologies for the long delay in replying, this is just a quick update to say the token serialisation function is being updated in 1.6.0 as part of a broader scope complete new QueryBuilder being written in phantom.

This issue will be addressed as part of the existing roadmap. Many thanks for reporting it.

**Comment by alexflav23** [comment]
@ehartsuyker We have fixed this bug as part of the roadmap to phantom 2.0.0, which will make prime time very very soon, hopefully next week. Beyond that, you could make everything work as you describe by simply using the normal equals, which would generate the query in the second example:

```scala

SELECT * FROM LogLookUpTable WHERE type = '<type>' and yearmonth = <yearmonth>

```

**Comment by ehartsuyker** [comment]
We moved away from this because we couldn't wait for a fix, but were the types changed so that a normal equals in a where clauses compiles? Or is that not what you mean?

**Comment by alexflav23** [comment]
@ehartsuyker A normal ```eqs``` would have compiled back then too, without the need of a token function. I can add a test for this specific scenario in the latest branch, just to be extra sure.

**Comment by ehartsuyker** [comment]
Awesome. Thanks for being on top of this. Thumbs up.
