### ISSUE TITLE
Unresolved sbt dependencies

### ISSUE THREAD

**Issue by brenttheisen** [websudos/phantom#179]
I am unable to get sbt to resolve the `com.twitter#finagle-zookeeper_2.11;6.24.0` and `com.websudos#util-testing_2.11;0.5.0` dependencies. Tried to find what resolvers need to be added for these dependencies but its not clear where either of them has moved to.

Full sbt output:

```
brent@wasted:~/phantom$ sbt clean compile
[info] Loading project definition from /Users/brent/phantom/project
[info] Set current project to phantom (in build file:/Users/brent/phantom/)
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[success] Total time: 0 s, completed Jan 21, 2015 4:37:10 PM
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[info] Updating {file:/Users/brent/phantom/}phantom...
[info] Updating {file:/Users/brent/phantom/}phantom-zookeeper...
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.1 ...
[info] Done updating.
[info] Resolving com.twitter#finagle-zookeeper_2.11;6.24.0 ...
[warn]  module not found: com.twitter#finagle-zookeeper_2.11;6.24.0
[warn] ==== local: tried
[warn]   /Users/brent/.ivy2/local/com.twitter/finagle-zookeeper_2.11/6.24.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/finagle-zookeeper_2.11/6.24.0/finagle-zookeeper_2.11-6.24.0.pom
[warn] ==== Typesafe repository snapshots: tried
[warn]   http://repo.typesafe.com/typesafe/snapshots/com/twitter/finagle-zookeeper_2.11/6.24.0/finagle-zookeeper_2.11-6.24.0.pom
[warn] ==== Typesafe repository releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/twitter/finagle-zookeeper_2.11/6.24.0/finagle-zookeeper_2.11-6.24.0.pom
[warn] ==== Sonatype repo: tried
[warn]   https://oss.sonatype.org/content/groups/scala-tools/com/twitter/finagle-zookeeper_2.11/6.24.0/finagle-zookeeper_2.11-6.24.0.pom
[warn] ==== Sonatype releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/twitter/finagle-zookeeper_2.11/6.24.0/finagle-zookeeper_2.11-6.24.0.pom
[warn] ==== Sonatype snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/twitter/finagle-zookeeper_2.11/6.24.0/finagle-zookeeper_2.11-6.24.0.pom
[warn] ==== Sonatype staging: tried
[warn]   http://oss.sonatype.org/content/repositories/staging/com/twitter/finagle-zookeeper_2.11/6.24.0/finagle-zookeeper_2.11-6.24.0.pom
[warn] ==== Java.net Maven2 Repository: tried
[warn]   http://download.java.net/maven/2/com/twitter/finagle-zookeeper_2.11/6.24.0/finagle-zookeeper_2.11-6.24.0.pom
[warn] ==== Twitter Repository: tried
[warn]   http://maven.twttr.com/com/twitter/finagle-zookeeper_2.11/6.24.0/finagle-zookeeper_2.11-6.24.0.pom
[warn] ==== Websudos releases: tried
[warn]   http://maven.websudos.co.uk/ext-release-local/com/twitter/finagle-zookeeper_2.11/6.24.0/finagle-zookeeper_2.11-6.24.0.pom
[warn] ==== Websudos snapshots: tried
[warn]   http://maven.websudos.co.uk/ext-snapshot-local/com/twitter/finagle-zookeeper_2.11/6.24.0/finagle-zookeeper_2.11-6.24.0.pom
[info] Resolving com.websudos#util-testing_2.11;0.5.0 ...
[warn]  module not found: com.websudos#util-testing_2.11;0.5.0
[warn] ==== local: tried
[warn]   /Users/brent/.ivy2/local/com.websudos/util-testing_2.11/0.5.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/websudos/util-testing_2.11/0.5.0/util-testing_2.11-0.5.0.pom
[warn] ==== Typesafe repository snapshots: tried
[warn]   http://repo.typesafe.com/typesafe/snapshots/com/websudos/util-testing_2.11/0.5.0/util-testing_2.11-0.5.0.pom
[warn] ==== Typesafe repository releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/websudos/util-testing_2.11/0.5.0/util-testing_2.11-0.5.0.pom
[warn] ==== Sonatype repo: tried
[warn]   https://oss.sonatype.org/content/groups/scala-tools/com/websudos/util-testing_2.11/0.5.0/util-testing_2.11-0.5.0.pom
[warn] ==== Sonatype releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/websudos/util-testing_2.11/0.5.0/util-testing_2.11-0.5.0.pom
[warn] ==== Sonatype snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/websudos/util-testing_2.11/0.5.0/util-testing_2.11-0.5.0.pom
[warn] ==== Sonatype staging: tried
[warn]   http://oss.sonatype.org/content/repositories/staging/com/websudos/util-testing_2.11/0.5.0/util-testing_2.11-0.5.0.pom
[warn] ==== Java.net Maven2 Repository: tried
[warn]   http://download.java.net/maven/2/com/websudos/util-testing_2.11/0.5.0/util-testing_2.11-0.5.0.pom
[warn] ==== Twitter Repository: tried
[warn]   http://maven.twttr.com/com/websudos/util-testing_2.11/0.5.0/util-testing_2.11-0.5.0.pom
[warn] ==== Websudos releases: tried
[warn]   http://maven.websudos.co.uk/ext-release-local/com/websudos/util-testing_2.11/0.5.0/util-testing_2.11-0.5.0.pom
[warn] ==== Websudos snapshots: tried
[warn]   http://maven.websudos.co.uk/ext-snapshot-local/com/websudos/util-testing_2.11/0.5.0/util-testing_2.11-0.5.0.pom
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.twitter#finagle-zookeeper_2.11;6.24.0: not found
[warn]  :: com.websudos#util-testing_2.11;0.5.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.twitter:finagle-zookeeper_2.11:6.24.0 (/Users/brent/phantom/project/Build.scala#L217)
[warn]            +- com.websudos:phantom-zookeeper_2.11:1.5.0
[warn]          com.websudos:util-testing_2.11:0.5.0 (/Users/brent/phantom/project/Build.scala#L217)
[warn]            +- com.websudos:phantom-zookeeper_2.11:1.5.0
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
[warn] Credentials file /Users/brent/.ivy2/.credentials does not exist
sbt.ResolveException: unresolved dependency: com.twitter#finagle-zookeeper_2.11;6.24.0: not found
unresolved dependency: com.websudos#util-testing_2.11;0.5.0: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
        at sbt.IvySbt.withIvy(Ivy.scala:123)
        at sbt.IvySbt.withIvy(Ivy.scala:120)
        at sbt.IvySbt$Module.withModule(Ivy.scala:151)
        at sbt.IvyActions$.updateEither(IvyActions.scala:157)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[error] (phantom-zookeeper/*:update) sbt.ResolveException: unresolved dependency: com.twitter#finagle-zookeeper_2.11;6.24.0: not found
[error] unresolved dependency: com.websudos#util-testing_2.11;0.5.0: not found
[error] Total time: 9 s, completed Jan 21, 2015 4:37:19 PM
```

**Comment by alexflav23** [comment]
Hi @brenttheisen,

The issue is with our managed Maven repository which we are experiencing issues with. We are aware of the problem and working on it already, and all the core websudos projects will be moved to Maven Central.

We will make sure to update everyone via Twitter and Github and fix the issue as soon as possible, within the next few hours! Hope this helps.

Regards,

**Comment by brenttheisen** [comment]
OK, thanks @alexflav23! I realize deploying to Maven Central/Sonatype Nexus is a lot more difficult than it sounds so no rush.

**Comment by sjohnc** [comment]
Any resolution to this yet?

**Comment by alexflav23** [comment]
Hi @sjohnc @brenttheisen  The issues in question should now be fixed, we've just republished those dependencies to our Maven repository. Please let us know if you experience further issues.

**Comment by brenttheisen** [comment]
Works for me now. Thank you.

**Comment by jelmo** [comment]
Hi. I have just experienced this issue: SBT cannot resolve com.twitter#finagle-zookeeper_2.11;6.24.0. 
I looked on Maven Central, Twitter and Websudos repositories and the library is nowhere to be found. 

It should be noted that just a few days ago SBT could resolve it without any problem, from the Websudos repository (http://maven.websudos.co.uk/ext-release-local). Was the library recently removed from this repository?

**Comment by alexflav23** [comment]
Hi @jelmo,

We are experiencing issues with our Artifactory installation and had to install from scratch a second time, the 1st being the last time this issue was open. It's already being addresses as we speak.

Apologies for any inconvenience!

Regards,

**Comment by jelmo** [comment]
It works now. Thank you.

**Comment by brenttheisen** [comment]
I think this is happening again. Can anyone else confirm?

**Comment by brenttheisen** [comment]
Hi @alexflav23. It looks like this issue is happening again and its causing a lot of issues with our build process and delaying release of a blog post I wrote about Phantom. Can you please republish `com.twitter#finagle-zookeeper` to your Maven repository? Thanks.

**Comment by RobColeman** [comment]
I'm having this issue with 

com.twitter#finagle-zookeeper_2.10;6.24.0
and 
org.cassandraunit#cassandra-unit;2.0.2.6

even with both of these are in my resolvers:
  "twitter"                          at "http://maven.twttr.com",
  "websudos-repo"                    at "http://maven.websudos.co.uk/ext-release-local",

**Comment by alexflav23** [comment]
@RobColeman Hi, please read the README as we have long moved the infrastructure to Bintray and the Maven Websudos repository is no longer available.
