### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.reflect.TypeToken.isPrimitive

### ISSUE THREAD

**Issue by GoldenZero** [websudos/phantom#397]
Hi,
I'm trying to update phantom-dsl from 1.10.1 to any >1.18.0 but I'm getting this error:

java.lang.NoSuchMethodError: com.google.common.reflect.TypeToken.isPrimitive()Z
	at com.datastax.driver.core.TypeCodec.<init>(TypeCodec.java:406)
	at com.datastax.driver.core.TypeCodec.<init>(TypeCodec.java:400)
	at com.datastax.driver.core.TypeCodec$BlobCodec.<init>(TypeCodec.java:947)
	at com.datastax.driver.core.TypeCodec$BlobCodec.<clinit>(TypeCodec.java:944)
	at com.datastax.driver.core.TypeCodec.blob(TypeCodec.java:248)
	at com.datastax.driver.core.CodecRegistry.<clinit>(CodecRegistry.java:159)
	at com.datastax.driver.core.Configuration$Builder.build(Configuration.java:268)
	at com.datastax.driver.core.Cluster$Builder.getConfiguration(Cluster.java:1232)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:115)
	at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:182)
	at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:1249)
	at com.websudos.phantom.connectors.DefaultSessionProvider.<init>(DefaultSessionProvider.scala:31)
	at com.websudos.phantom.connectors.KeySpaceDef.<init>(Keyspace.scala:63)
	at com.websudos.phantom.connectors.KeySpaceBuilder.keySpace(KeySpaceBuilder.scala:39)

**Comment by alexflav23** [comment]
Hi @GoldenZero ,

You are obviously getting a version conflict because you have a previous version of Guava in the classpath(or possibly a newer one than the one phantom uses). Try removing any direct references to Guava from your build or find out which is the offending dependency.

Regards.

**Comment by GoldenZero** [comment]
Hi @alexflav23 

My application depends only on guava 16.0.1 which's the same version used by phantom


```
[info]   +-com.typesafe.play:play-ws_2.11:2.3.4
[info]   | +-com.google.guava:guava:16.0.1
```

```
[info]   +-com.websudos:phantom-dsl_2.11:1.20.1
[info]   | +-ch.qos.logback:logback-classic:1.1.3
[info]   | | +-ch.qos.logback:logback-core:1.1.3
[info]   | | +-org.slf4j:slf4j-api:1.7.10 (evicted by: 1.7.12)
[info]   | | +-org.slf4j:slf4j-api:1.7.12
[info]   | | +-org.slf4j:slf4j-api:1.7.7 (evicted by: 1.7.10)
[info]   | | 
[info]   | +-com.chuusai:shapeless_2.11:2.2.4
[info]   | | +-org.scala-lang:scala-library:2.11.7
[info]   | | 
[info]   | +-com.datastax.cassandra:cassandra-driver-core:3.0.0-alpha4
[info]   | | +-com.codahale.metrics:metrics-core:3.0.2
[info]   | | | +-org.slf4j:slf4j-api:1.7.12
[info]   | | | +-org.slf4j:slf4j-api:1.7.5 (evicted by: 1.7.12)
[info]   | | | 
[info]   | | +-com.google.guava:guava:16.0.1
[info]   | | +-io.netty:netty-handler:4.0.27.Final
[info]   | |   +-io.netty:netty-buffer:4.0.27.Final
[info]   | |   | +-io.netty:netty-common:4.0.27.Final
[info]   | |   | 
[info]   | |   +-io.netty:netty-codec:4.0.27.Final
[info]   | |   | +-io.netty:netty-transport:4.0.27.Final
[info]   | |   |   +-io.netty:netty-buffer:4.0.27.Final
[info]   | |   |     +-io.netty:netty-common:4.0.27.Final
[info]   | |   |     
[info]   | |   +-io.netty:netty-transport:4.0.27.Final
[info]   | |     +-io.netty:netty-buffer:4.0.27.Final
[info]   | |       +-io.netty:netty-common:4.0.27.Final
[info]   | |       
```

**Comment by alexflav23** [comment]
hi @GoldenZero ,

You should double check that or remove your Guava deps altogether, let phantom set it's own course. There's nothing we can do to help anyway since this is a local conflict issue.

Try removing your stuff and try again, at least you will isolate the problem.

Regards.

**Comment by GoldenZero** [comment]
Thank you @alexflav23 
The issue is solved now, the problem was conflict with guava jdk5, and it was solved by updating the google-api-java-client
more details: https://github.com/google/google-api-java-client/issues/903

Cheers,
