### ISSUE TITLE
Creation of keyspace permission problems

### ISSUE THREAD

**Issue by gvolpe** [websudos/phantom#406]
Hi, I'm actually having problems to get a connection when the [DefaultSessionProvider](https://github.com/websudos/phantom/blob/develop/phantom-connectors/src/main/scala/com/websudos/phantom/connectors/DefaultSessionProvider.scala#L40) tries to create a keyspace if not exists. I think this action should be configurable.

This is the exception:
```
Exception in thread "main" com.datastax.driver.core.exceptions.UnauthorizedException: User test has no CREATE permission on <all keyspaces> or any of its parents
	at com.datastax.driver.core.exceptions.UnauthorizedException.copy(UnauthorizedException.java:36)
	at com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:289)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:205)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:52)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:36)
	at com.websudos.phantom.connectors.DefaultSessionProvider.initKeySpace(DefaultSessionProvider.scala:44)
	at com.websudos.phantom.connectors.DefaultSessionProvider.createSession(DefaultSessionProvider.scala:53)
	at com.websudos.phantom.connectors.DefaultSessionProvider$$anonfun$getSession$1.apply(DefaultSessionProvider.scala:57)
	at com.websudos.phantom.connectors.DefaultSessionProvider$$anonfun$getSession$1.apply(DefaultSessionProvider.scala:57)
	at com.websudos.phantom.connectors.Cache$Lazy.get$lzycompute(DefaultSessionProvider.scala:77)
	at com.websudos.phantom.connectors.Cache$Lazy.get(DefaultSessionProvider.scala:77)
	at com.websudos.phantom.connectors.Cache.getOrElseUpdate(DefaultSessionProvider.scala:96)
	at com.websudos.phantom.connectors.DefaultSessionProvider.getSession(DefaultSessionProvider.scala:57)
	at com.websudos.phantom.connectors.Connector$class.session(Connector.scala:65)
	at com.paddypower.inspector.service.InspectorService$inboundMessages$.session$lzycompute(InspectorService.scala:38)
	at com.paddypower.inspector.service.InspectorService$inboundMessages$.session(InspectorService.scala:38)
	at com.paddypower.inspector.model.InboundMessagesDao.findById(InboundMessage.scala:32)
	at com.paddypower.inspector.Inspector$.delayedEndpoint$com$paddypower$inspector$Inspector$1(Inspector.scala:10)
	at com.paddypower.inspector.Inspector$delayedInit$body.apply(Inspector.scala:6)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.paddypower.inspector.Inspector$.main(Inspector.scala:6)
	at com.paddypower.inspector.Inspector.main(Inspector.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.datastax.driver.core.exceptions.UnauthorizedException: User test has no CREATE permission on <all keyspaces> or any of its parents
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:102)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:140)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:293)
	at com.datastax.driver.core.RequestHandler.onSet(RequestHandler.java:455)
	at com.datastax.driver.core.Connection$Dispatcher.messageReceived(Connection.java:734)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
```

The problem is the user "test" does not have permissions to create a keyspace, which is right, but it seems the sentence "CREATE KEYSPACE IF NOT EXISTS" check for creation permissions.

Thanks,
Gabriel.

**Comment by alexflav23** [comment]
Hi @gvolpe,

We will look into this, happy to see phantom rocking the boat at Paddy. Should hopefully be a quick fix and release, I will keep you posted.

Regards.

**Comment by gvolpe** [comment]
Thanks Alex! At the moment I'm using it with this workaround: https://github.com/gvolpe/phantom-ssl-extension

**Comment by Ciaran0** [comment]
Hi @gvolpe , I think I've had a similar problem before #242

**Comment by alexflav23** [comment]
Hi @Ciaran0 , @gvolpe ,

They are indeed related, we are working very hard to push the new product out and you should be able to buy subscriptions to it very very shortly, we are hoping the final cut will be ready to go live end of February to mid March.

It addresses full DSE support, automated migrations, a far more powerful QueryBuilder to allow for more advanced topology patterns, and the UDTs everyone has been waiting for, all 100% typesafe and reactive. We are also creating a full book of tutorials on Cassandra, Phantom and Spark that will be offered for free with any subscription.

Regards.

**Comment by alexflav23** [comment]
Hi @gvolpe @Ciaran0,

Using authentication is completely possible, as well as native SSL. Basically, the default session provider already allows you to chain all the normal properties of the cluster builder.

You can already use for example the following:

```scala
val connector = ContactPoint.local.withClusterBuilder(
    _.withAuthProvider(new PlainTextAuthProvider("test", "test"))
  ).keySpace(space.name)
```

Basically whatever methods already exist on the cluster builder are available to call via `withClusterBuilder`.

Regards.
