### ISSUE TITLE
Issue with custom column types 

### ISSUE THREAD

**Issue by lahirug** [websudos/phantom#410]
I created a custom column type as below and worked fine but when I try using Long instead timestamp I get an error. Please find my scala code and error below.

  /** Helper to store durations without remembering the unit */
  implicit object DurationPrimitive extends Primitive[Duration] {
    override type PrimitiveType = Long
    val cassandraType = CQLSyntax.Types.Long
    def fromRow(row: Row, name: String): Option[Duration] = fromRow(name, row).toOption
    override def asCql(value: Duration): String = {
      value.toMillis.toString
    }
    override def fromRow(column: String, row: Row): Try[Duration] = nullCheck(column, row) {
      r => Duration.ofMillis(r.getLong(column))
    }
    override def clz: Class[Long] = classOf[Long]
    override def fromString(value: String): Duration = Duration.ofMillis(value.toLong)
  }

Error

com.datastax.driver.core.exceptions.InvalidQueryException: Unknown type local.long
    at com.datastax.driver.core.Responses$Error.asException(Responses.java:124)
    at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:180)
    at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:186)
    at com.datastax.driver.core.RequestHandler.access$2300(RequestHandler.java:44)
    at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:754)
    at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:576)
    at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1007)
    at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:930)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at java.lang.Thread.run(Thread.java:745)

**Comment by alexflav23** [comment]
You may need to specify `java.lang.Long` as opposed to `scala.Long`. Look at `LongPrimitive` for instance. The driver is pretty picky about that.

```override type PrimitiveType = java.lang.Long```

**Comment by lahirug** [comment]
@alexflav23 Thanks a lot, it worked, and can I keep 
 val cassandraType = CQLSyntax.Types.Timestamp as it is ? I tried to use Long instead but in that case I don't have long in my Codec Data for java driver in com.datastax.driver.core.DataType.

**Comment by lahirug** [comment]
@alexflav23 I noticed the actual issue is with line,
val cassandraType = CQLSyntax.Types.Timestamp because there is no type associated in java driver for Long  in com.datastax.driver.core.DataType. Sorry if I am wrong.

**Comment by alexflav23** [comment]
I'm not sure I follow on what's missing. Have a look at `LongPrimitive`.

```scala

implicit object LongPrimitive extends Primitive[Long] {

    override type PrimitiveType = java.lang.Long

    def asCql(value: Long): String = value.toString

    override def cassandraType: String = CQLSyntax.Types.BigInt

    override def fromString(value: String): Long = value.toLong

    override def fromRow(column: String, row: Row): Try[Long] = nullCheck(column, row) {
      r => r.getLong(column)
    }

    override def clz: Class[java.lang.Long] = classOf[java.lang.Long]
  }
```

**Comment by lahirug** [comment]
implicit object InstantPrimitive extends Primitive[Instant] {
    override type PrimitiveType = Long
    val cassandraType = CQLSyntax.Types.BigInt
    def fromRow(row: Row, name: String): Option[Instant] = fromRow(name, row).toOption
    override def asCql(value: Instant): String = {
      value.toEpochMilli.toString
    }
    override def fromRow(column: String, row: Row): Try[Instant] = nullCheck(column, row) {
      r => Instant.ofEpochMilli(r.getLong(column))
    }
    override def clz: Class[Long] = classOf[Long]
    override def fromString(value: String): Instant = Instant.parse(value)
  }

Above worked.

**Comment by alexflav23** [comment]
Hi @lahirug,

Cassandra type is not used by the Java driver, it's used by phantom for schema autogeneration and by the query builder throughout. The Java driver will only care about the `clz`and `PrimitiveType`, the rest is just phantom.

Obviously you want to keep things consistent, I just thought it may be useful advice for the future.

**Comment by lahirug** [comment]
Thanks for the response Alex. But FYI just want to share the experience in case this is an issue in phantom. I changed the code to use CQLSyntax.Types.Long for cassandraType it gave me the above error everything else is same. But when I use BigInt or any other type (ex: Timestamp) all works fine.

ex: This code never worked. 

```implicit object InstantPrimitive extends Primitive[Instant] {
    override type PrimitiveType = Long
    val cassandraType = CQLSyntax.Types.Long
    def fromRow(row: Row, name: String): Option[Instant] = fromRow(name, row).toOption
    override def asCql(value: Instant): String = {
      value.toEpochMilli.toString
    }
    override def fromRow(column: String, row: Row): Try[Instant] = nullCheck(column, row) {
      r => Instant.ofEpochMilli(r.getLong(column))
    }
    override def clz: Class[Long] = classOf[Long]
    override def fromString(value: String): Instant = Instant.parse(value)
  }```

But this worked.

```implicit object InstantPrimitive extends Primitive[Instant] {
    override type PrimitiveType = Long
    val cassandraType = CQLSyntax.Types.BigInt  // <or Timestampe>
    def fromRow(row: Row, name: String): Option[Instant] = fromRow(name, row).toOption
    override def asCql(value: Instant): String = {
      value.toEpochMilli.toString
    }
    override def fromRow(column: String, row: Row): Try[Instant] = nullCheck(column, row) {
      r => Instant.ofEpochMilli(r.getLong(column))
    }
    override def clz: Class[Long] = classOf[Long]
    override def fromString(value: String): Instant = Instant.parse(value)
  }```

**Comment by alexflav23** [comment]
Hi @lahirug,

Thank you for sharing, I didn't expect the first version to work because `BigInt` is the Cassandra type for timestamps. I think `CQLSyntax.Types.Long` is actually not used in the codebase and was added long ago by accident. I will follow up and flag it for deletion as necessary.

Is `Instant` an `org.joda` primitive?

Regards.

**Comment by lahirug** [comment]
Hi Alex, 

Sorry for the late response.
This is java.time not joda, I think it would be very useful to have Column types for OffsetDateTime, Instant, Duration and ZoneOffset.

Regards
Lahiru
