### ISSUE TITLE
unresolved dependency.

### ISSUE THREAD

**Issue by mozartvn** [websudos/phantom#425]
Hi, I add some directives in sbt file, but I get unresolved dependency.
plz help me to solve this issues.

val phantomVersion = "1.21.5"

resolvers ++= Seq(
  "Typesafe repository snapshots" at "http://repo.typesafe.com/typesafe/snapshots/",
  "Typesafe repository releases" at "http://repo.typesafe.com/typesafe/releases/",
  "Sonatype repo"                    at "https://oss.sonatype.org/content/groups/scala-tools/",
  "Sonatype releases"                at "https://oss.sonatype.org/content/repositories/releases",
  "Sonatype snapshots"               at "https://oss.sonatype.org/content/repositories/snapshots",
  "Sonatype staging"                 at "http://oss.sonatype.org/content/repositories/staging",
  "Java.net Maven2 Repository"       at "http://download.java.net/maven/2/",
  "Twitter Repository"               at "http://maven.twttr.com",
  "Websudos releases"                at "https://dl.bintray.com/websudos/oss-releases/"
)

libraryDependencies ++= Seq(
  "com.websudos"  %% "phantom-dsl"                   % phantomVersion,
  "com.websudos"  %% "phantom-example"               % phantomVersion,
  "com.websudos"  %% "phantom-scalatra"              % phantomVersion,
  "com.websudos"  %% "phantom-thrift"                % phantomVersion,
  "com.websudos"  %% "phantom-testkit"               % phantomVersion,
  "com.websudos"  %% "phantom-udt"                   % phantomVersion,
  "com.websudos"  %% "phantom-zookeeper"             % phantomVersion
)

resolvers += "twitter-repo" at "http://maven.twttr.com"
resolvers += "websudos-repo" at "http://maven.websudos.co.uk/ext-release-local"

///////////////////////////////////////////
message in terminal of Intellij 

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.websudos#phantom-dsl_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-dsl_2.11;1.21.5 {compile=[default(compile)]}:
[warn]  URI has an authority component
[warn]  URI has an authority component
[warn]  :: com.websudos#phantom-example_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-example_2.11;1.21.5 {compile=[default(compile)]}:
[warn]  URI has an authority component
[warn]  URI has an authority component
[warn]  :: com.websudos#phantom-scalatra_2.11;1.21.5: URI has an authority component
[warn]  :: com.websudos#phantom-thrift_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-thrift_2.11;1.21.5 {compile=[default(compile)]}:
[warn]  URI has an authority component
[warn]  URI has an authority component
[warn]  :: com.websudos#phantom-testkit_2.11;1.21.5: URI has an authority component
[warn]  :: com.websudos#phantom-udt_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-udt_2.11;1.21.5 {compile=[default(compile)]}:
[warn]  URI has an authority component
[warn]  URI has an authority component
[warn]  :: com.websudos#phantom-zookeeper_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-zookeeper_2.11;1.21.5 {compile=[default(compile)]}:
[warn]  URI has an authority component
[warn]  URI has an authority component
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]

unresolved dependency: com.websudos#phantom-example_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-example_2.11;1.21.5 {compile=[default(compile)]}:
        URI has an authority component
        URI has an authority component

unresolved dependency: com.websudos#phantom-scalatra_2.11;1.21.5: URI has an authority component
unresolved dependency: com.websudos#phantom-thrift_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-thrift_2.11;1.21.5 {compile=[default(compile)]}:
        URI has an authority component
        URI has an authority component

unresolved dependency: com.websudos#phantom-testkit_2.11;1.21.5: URI has an authority component
unresolved dependency: com.websudos#phantom-udt_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-udt_2.11;1.21.5 {compile=[default(compile)]}:
        URI has an authority component
        URI has an authority component

unresolved dependency: com.websudos#phantom-zookeeper_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-zookeeper_2.11;1.21.5 {compile=[default(compile)]}:
        URI has an authority component
        URI has an authority component

        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
        at xsbt.boot.Using$.withResource(Using.scala:11)
        at xsbt.boot.Using$.apply(Using.scala:10)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:127)
        at sbt.IvySbt.withIvy(Ivy.scala:124)
        at sbt.IvySbt$Module.withModule(Ivy.scala:155)
        at sbt.IvyActions$.updateEither(IvyActions.scala:165)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.websudos#phantom-dsl_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-dsl_2.11;1.21.5 {compile=[de
fault(compile)]}:
[error]         URI has an authority component
[error]         URI has an authority component
[error]
[error] unresolved dependency: com.websudos#phantom-example_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-example_2.11;1.21.5 {compile=[default(compile)]}:
[error]         URI has an authority component
[error]         URI has an authority component
[error]
[error] unresolved dependency: com.websudos#phantom-scalatra_2.11;1.21.5: URI has an authority component
[error] unresolved dependency: com.websudos#phantom-thrift_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-thrift_2.11;1.21.5 {compile=[default(compile)]}:
[error]         URI has an authority component
[error]         URI has an authority component
[error]
[error] unresolved dependency: com.websudos#phantom-testkit_2.11;1.21.5: URI has an authority component
[error] unresolved dependency: com.websudos#phantom-udt_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-udt_2.11;1.21.5 {compile=[default(compile)]}:
[error]         URI has an authority component
[error]         URI has an authority component
[error]
[error] unresolved dependency: com.websudos#phantom-zookeeper_2.11;1.21.5: several problems occurred while resolving dependency: com.websudos#phantom-zookeeper_2.11;1.21.5 {compile=[default(compile)]}:
[error]         URI has an authority component
[error]         URI has an authority component
[error] Total time: 257 s, completed Feb 22, 2016 4:23:59 PM

**Comment by alexflav23** [comment]
Hi @mozartvn,

I don't think is explicitly related to phantom, but rather it's got something to do with Activator or the way your environment is set up. You could try phantom `1.22.0` just in case as that one is published on Maven Central, but otherwise have a look [here](http://stackoverflow.com/questions/30624099/sbt-0-13-8-uri-has-an-authority-component).

There may be something off in our activator template if you have used it(please do let me know), which we will correct asap if necessary.

Regards,
Flavian

**Comment by mozartvn** [comment]
thanks @alexflav23 

My issue  has passed.

The problems really is : I can not connect to 

resolvers += "websudos-repo" at "http://maven.websudos.co.uk/ext-release-local"

( following http://blog.websudos.com/2015/04/04/a-series-on-phantom-part-1-getting-started-with-phantom/ )

So I change resolver to  http://mvnrepository.com & change to phantom version 1.22.0.

it works fine ! 

Regards.
Mozartvn
